language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0

before_script:
    - phpenv rehash
    - composer install --dev

script:
    - find ./src/ -name "*.php" -exec php -l {} \;
    - php scripts/phpcs CodeSniffer.php CodeSniffer --standard=PSR2 --report=full src
    - vendor/bin/phpunit --configuration phpunit.xml --coverage-text

